language: java
dist: trusty

sudo: true

dist: trusty

jdk:
  - oraclejdk8

before_script:
  - pip install --user codecov

script:
  - jdk_switcher use oraclejdk8
  - mvn clean verify

after_success:
  - codecov
