endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true

server:
  port: 8086
  compression:
    enabled: true
    mime-types: "application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript"

dataservice:
  redis-host: localhost
  redis-port: 30001
  oauth2-token-info-url: ${TOKENINFO_URL:http://localhost:10080/oauth2/tokeninfo}
  kairosdb-write-urls:
    - ["http://localhost:38083"]
  oauth2-scopes:
    getApi: "#oauth2.hasScope('zmon_data.read_all') || (#oauth2.hasScope('uid') && #oauth2.hasRealm('/employees'))"
    putApi: "#oauth2.hasScope('zmon_data.read_all') || (#oauth2.hasScope('uid') && #oauth2.hasRealm('/employees'))"
    deleteApi: "#oauth2.hasScope('zmon_data.read_all') || (#oauth2.hasScope('uid') && #oauth2.hasRealm('/employees'))"

spring:
  redis:
    host: localhost
    port: 30001
    database: 0
    pool:
      max-active: 10
      max-idle: 4
      min-idle: 2

logging:
  level:
    org.springframework.web: ERROR
    de.zalando.zmon.dataservice: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /tmp/application.log