endpoints:
  enabled: false
  metrics:
    enabled: true

server:
  port: 8086

dataservice:
  redis-host: localhost
  redis-port: 6379
  oauth2-token-info-url: http://localhost:54321/oauth2/tokeninfo
  oauth2-scopes:
    getApi: "#oauth2.hasScope('zmon_data.read_all') || #oauth2.hasScope('uid')"
    getRest: "#oauth2.hasScope('zmon_data.read_all') || #oauth2.hasScope('uid')"
    putApi: "#oauth2.hasScope('zmon_data.read_all') || #oauth2.hasScope('uid')"
    deleteApi: "#oauth2.hasScope('zmon_data.read_all') || #oauth2.hasScope('uid')"


spring:
  redis:
    pool:
      max-active: 10
      max-idle: 4
      min-idle: 2